### ISSUE TITLE
Change team icon doesn't work

### ISSUE THREAD

**Issue by rafiki270** [Einstore/EinstoreAdmin#21] opened 2019-04-11 17:31 UTC

**Comment by ViliamKopecky** [comment] 2019-04-15 18:08
What do you mean?

**Comment by rafiki270** [comment] 2019-04-15 18:26
If the team is changed, the middle top of the screen Icon stays the same

**Comment by ViliamKopecky** [comment] 2019-04-15 18:49
Duplicate of https://github.com/Einstore/EinstoreAdmin/issues/8

**Closed by ViliamKopecky** 2019-04-15 18:49 UTC
